### ISSUE TITLE
Potential memory leaks

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qps#101]
##### Expected Behavior
The memory should not leak

##### Current Behavior
Memory probably leaks

##### Possible Solution
Rework
https://github.com/lxqt/qps/blob/master/src/command.cpp#L256-L271
https://github.com/lxqt/qps/blob/master/src/commanddialog.cpp#L132

[This](https://github.com/lxqt/qps/blob/master/src/misc.cpp#L641) code also checks parent against null first, then uses the pointer as if no check was performed...

**Comment by tsujan** [comment]
@shlyakpavel Why don't you make a PR?

**Comment by shlyakpavel** [comment]
@tsujan Left this not to forget. I'll try make it later. It probably needs deeper research on "what this code does" and "why didn't we face it before" (for the null pointer check especially)

**Comment by tsujan** [comment]
@shlyakpavel 

qps's code is very old (I think it was written for Qt3) and isn't written by LXQt devs. Most widgets are drawn in wrong ways.

It would be nice if you polish and modernize it.

**Comment by shlyakpavel** [comment]
Unfortunately, I can't say I have seen much code in my life. But this project is defenitely the worst I've ever seen. I wonder why lxqt ever took it. I have refactored a little part in my github, so I will defenitely leave pull request as at least something significant is done. I have already made it 757 lines of code less, but still there is MUCH to rework

**Comment by agaida** [comment]
this is Qt archaeology at finest - the base code is from the last century and still works more or less well :D

**Comment by tsujan** [comment]
@shlyakpavel This project was very nice in its own time -- probably before 2000 -- and the fact that it still works shows how efficient Qt is (compared to GTK, for example.

We took it to update its code in our free time but our free time is taken by other projects. So, patches are very welcome.

**Comment by agaida** [comment]
And now a bit LXQt history - https://github.com/lxqt/qps/issues/33 - @shlyakpavel you are not alone :sunglasses:

**Comment by tsujan** [comment]
BTW, my reaction to its code was like yours the first time I saw it. However, after I was told that it was so old, I was surprised.

IMO, it can be saved but, yes, it'll need a lot of work. I wanted to start that work but my estimation of my free time was so wrong; I'm really busy with LXQt and other projects.

@agaida, again, we wrote the same thing at the same time ;)

**Comment by shlyakpavel** [comment]
I have read an issue above. I try my best to be careful, but some places look so unclear, that I can still break something.
As for my fork - can you check if I'm going a right direction?

**Comment by tsujan** [comment]
> As for my fork - can you check if I'm going a right direction?

Sorry, I can't check all of them but if you make PRs, so that *each PR is related only to one kind of change/fix*, they could be reviewed later.

All in all, it's good to have such fixes but, as mentioned above, the problems are deeper. For example, the header is drawn in a very wrong way (perhaps, it was the only way with Qt3/Qt2), the branch lines are terrible, etc.

**Comment by tsujan** [comment]
Bad news: I'd fixed a lot of GUI problems last year (especially, branch lines) but I can't find my patches anywhere; most probably, I deleted them inadvertently :(

**Comment by shlyakpavel** [comment]
@tsujan Well. Its not that easy to split all the changes I have done into separate pull request. One and the only change is unused code removal.
I understand its not easy to check, but still...
Either I send it in PR "as is" or I probably should go for a another project. There are plenty of modern Qt task managers on github so it's probably easier to adopt one of these...
Anyway, thanks a lot for working on LxQt. From my point of view, it's the most promising desktop environment and it's already great for many users :)
P. S. I have PVS studio static analysis tool  license now, so I can check some parts of lxqt. What repository I should go for with it?

**Comment by agaida** [comment]
@shlyakpavel - it might be worth to split things in smaller parts - you will have the same problem in every project - the philosophy of git is to commit fast and often - and it make a lot of sense to do so. Anyways, it will ease the work of others - and in case of havoc it will make fixing things a lot easier.

**Comment by tsujan** [comment]
> Either I send it in PR "as is"

Please read @agaida's comment above!

> P. S. I have PVS studio static analysis tool license now, so I can check some parts of lxqt. What repository should I go first?

Whichever you choose, except for `lxqt-config`, because I'm making heavy changes to it and will add PRs after the next release.

Thanks for finding and fixing code problems!

**Comment by plonibarploni** [comment]
I just installed qps and found it to be really nice (it does everything I wanted), until I started noticing the memory usage climbing. When I first took note of it, it was at 118MB; currently it's at 148MB. I came here to report it, and I saw this.
