### ISSUE TITLE
lxqt-build-tools minimum version requirement is a bit too strict

### ISSUE THREAD

**Issue by barsnick** [lxqt/qps#110]
Since 1.10.19, qps's build requires lxqt-build-tools. CMakeLists.txt enforces a minimum version of 0.6.0. Tests show that 0.5.0 is sufficient for building.

##### Expected Behavior
Build successfully with lxqt-build-tools 0.5.0.

##### Current Behavior
Refuses to build with lxqt-build-tools before 0.6.0.

##### Possible Solution
In CMakeLists.txt, change the setting of LXQTBT_MINIMUM_VERSION from 0.6.0 to 0.5.0. (Sorry, to banal for a PR.)

##### Context
I couldn't build on Fedora F29, which provides lxqt-build-tools 0.5.0. 0.6.0 was only released a few days ago, and many distributions will be behind.

(Fedora F28 still provides 0.3.2 for some reason. Spoiler: 0.3.2 isn't sufficient for building.)

I haven't actually tested the resulting binary yet, but I assume lxqt-build-tools only affects the build process.

##### System Information
* Distribution & Version: Fedora F29
* Kernel: irrelevant
* Qt Version: 
* Package version: 1.10.19

**Comment by agaida** [comment]
not a bug - and no, not to strict. We want it that way for some reasons. Have a look into the build order. if you want qps - build lxqt-build-tools first.
