### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qps#133]
https://github.com/lxqt/qps/blob/c78b4063bfe4b6defb4d4f1bbc14a816763cfaff/src/proc.cpp#L234-L262
Path > 256 chars can cause overflow. I am afraid it can be used to rewrite stack return address and cause privilege escalation for some process.
The function returns true anyway. So the proposal is either to get rid of the code or to switch it to use QString instead to these creepy char arrays.
Any ideas here?

**Comment by tsujan** [comment]
The code is very very old; none of us has written it and it still works only because of Qt's magic. Please do as you see appropriate!
