### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qps#138]
@agaida this is probably a comment for you
This project has two Russian translations on weblate: ru_RU and ru
ru is 100% complete and nice
ru_RU is almost nothing
However, qt loads ru_RU by default so the translation is broken. Could you please delete ru_RU and keep only ru?

**Comment by shlyakpavel** [comment]
Here is what I mean:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/19782228/63216760-32289200-c143-11e9-8cdf-d909f9f5802e.png">

**Comment by agaida** [comment]
ok - no problem

**Comment by shlyakpavel** [comment]
Thanks!
