### ISSUE TITLE
Part of code I need help with

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qps#140]
https://github.com/lxqt/qps/blob/2034adecce93cc406ebfdc592eb4c1dfe7c86d76/src/wchan.cpp#L99-L100
This call has obviously no sense but to leak resources. However, I do not understand the code logic. Would *should* the function above do? I really hope some of you guys can understand it better and give me a clue or fix it.

**Comment by tsujan** [comment]
`wchan.cpp` is a redundant file. I'll remove redundant files/functions/variables when I start to clean up the code: one PR for each file -- but not soon.
