### ISSUE TITLE
SWAP size is different

### ISSUE THREAD

**Issue by ito32bit** [lxqt/qps#187]
##### Expected Behavior

I want to watch Swap size.

##### Current Behavior

SWAP size is very large.
SWAP of Qps and SWAP of Top are different.

Screenshot:
![SWAP_screen-A](https://user-images.githubusercontent.com/52656419/66114643-400a7780-e60a-11e9-906f-ecfe776daffd.jpg)

##### Possible Solution

<https://github.com/lxqt/qps/blob/master/src/proc_linux.cpp#L804>  
<https://github.com/lxqt/qps/blob/master/src/proc_common.cpp#L216>  

```
&size:     669587×4096/1024=2678348 kB  (VmSize)
&resident: 102843×4096/1024=411372 kB   (VmRSS)
sizeK:     2678348-411372=2266976 kB    # SWAP field
```
I think that "&size" is not total memory but virtual memory(VmSize).
So I don't think that value of "sizeK" is Swap size.
I checked it and found it here.

Screenshot:
![VmSize_screen-A](https://user-images.githubusercontent.com/52656419/66114665-4e589380-e60a-11e9-90c0-d61484602035.jpg)

##### Steps to Reproduce (for bugs)

1. Add SWAP field
2. Run many appilications

##### Context

My PC have 2GB memory. Therefore, my PC requires SWAP. I want to watch Swap size.
However, many recent PCs have a lot of memory. SWAP may not be required.
This issue is not important.

##### System Information

* Distribution & Version: Ubuntu 18.04.3 LTS (i686)
* Kernel: 4.15.0-65-generic
* Qt Version: 5.9.5
* lxqt-build-tools Version: Build from source
* Package version: Build from source

**Comment by tsujan** [comment]
Interesting! I'll investigate it.

BTW, if you update to the latest git Qps, you'll get rid of GUI problems.

**Comment by tsujan** [comment]
Back to this:

The SWAP column definitely does NOT show the swap usage. My system almost never uses swap but the SWAP column shows big values. The swap usage size can be get from `/proc/*/status` → `VmSwap`

Now, some questions: Why the original author calculated SWAP in that way? Is there a difference between ancient kernels and recent ones? Or did he mean something else by "SWAP"?

More investigation is needed...

**Comment by tsujan** [comment]
Answers:

Apparently, there was no reliable way of calculating swap per process before kernel 2.6.18 (I found this by chance: http://sophie2.aero.jussieu.fr/distrib/Scientific%20Linux/5x/i386/by-pkgid/351d529f9beeb4e5d936a6d5e3e7813a/files/645). So, the original author used `VIRT – RES` for SWAP -- which is irrelevant now.

I added a few lines to the code for reading `/proc/*/status → VmSwap` and Qps showed 0 here (the correct value). But I should test with a system that uses swap (in VirtualBox?).

**Comment by ito32bit** [comment]
> But I should test with a system that uses swap (in VirtualBox?).

I think there will be more swap with the following settings :

```
sudo sysctl vm.swappiness=99					# Default: 60
sudo sysctl vm.vfs_cache_pressure=1				# Default: 100

sudo sysctl vm.dirty_background_ratio=90			# Default: 10  (10 %)
sudo sysctl vm.dirty_ratio=95					# Default: 20  (20%)

# Reboot is required to reset
```

<https://gist.github.com/ito32bit/cb331000cd1fa10f83f12ed4b84adeae>
<https://www.kernel.org/doc/Documentation/sysctl/vm.txt>

I think it is a little swap-out even if there is free memory.
I don't know much about swap. I think the server's administrators are very familiar with swap.
