### ISSUE TITLE
Unable to delete selected text inside main text box in linux app using DELETE key but can do so with only BACKSPACE. Please fix this!

### ISSUE THREAD

**Issue by roboirc** [lxqt/qps#237]
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
If by "main text box" you mean the filter line-edit, use `Escape`. `Delete` has another meaning in Qps.
