### ISSUE TITLE
Field in Menu is not translated

### ISSUE THREAD

**Issue by mkkDr2010** [lxqt/qps#271]
I noticed that Field in Menu bar is left without translation. There is missing translation function for the entry in line 214 of qpc,cpp, and corresponding source in .ts file. I added those manual in my files and the issue is corrected.

**Comment by stefonarch** [comment]
> I added those manual in my files and the issue is corrected.

You could try making a PR with your modifications.
```
git clone https://github.com/lxqt/qps
cd qps
git checkout -b add_missing_translation

```

apply your changes and compile to test.

```
git status
git add .
git commit -m "added field translation"
git push origin add_missing_translation
```

the last command gives you also the link for making a PR.

**Comment by mkkDr2010** [comment]
I tried but I have no permissions.
The command: git push origin add_missing_translation
exits with error
 Permission to lxqt/qps.git denied to mkkDr2010.

**Comment by stefonarch** [comment]
Ok, I thought you had cloned from your own repo.
You need to fork the qps repo, button on the top right.
then
```
git remote add mkkDr2010 https://github.com/mkkDr2010/qps
git push mkkDr2010  add_missing_translation
```
this should create a branch on your GH repo qps and there you can review files and open a PR.

**Comment by mkkDr2010** [comment]
Thanks for the instructions. I have made the PR and I hope that all went right.



Am Sonntag, Dezember 13, 2020, 12:18 PM schrieb Standreas <notifications@github.com>:




Ok, I thought you had cloned from your own repo.
You need to fork the qps repo, button on the top right.
then
git remote add mkkDr2010 https://github.com/mkkDr2010/qps
git push mkkDr2010  add_missing_translation

this should create a branch on your GH repo qps and there you can review files and open a PR.

**Comment by stefonarch** [comment]
There are 3 issues: one the PR should include only src/qps.ccp, probably your repo wasn't up do date and included your translation, and I think it should  be plural not singular. 

Second there are 2 missing spaces, I'm no coder but there are always present:
`m_field = new QMenu(tr("Field"), this);`
`m_field = new QMenu( tr( "Fields" ), this);`

For a one-line modification like this you can do it easier in github
https://github.com/lxqt/qps/blob/master/src/qps.cpp
 just hit the "edit" button (pencil) right to "blame", and change it and save it, it will go to your repo as patch-1 and should be fine.

**Comment by stefonarch** [comment]
Just saw that there are some other things to fix, and translations weren't updated for a long time, may translations are obsolete.
Will make a PR and include your line with credits.
