### ISSUE TITLE
 Custom fields are not persistent in debian

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qps#275]
##### Expected Behavior

Selection of  custom fields is permanently saved.
##### Current Behavior

Closing Qps custom selection is lost.
##### Possible Solution

Implement a "save" button instead of OK?
* Distribution & Version: debian bullseye, git checkout

**Comment by tsujan** [comment]
I use Qps only with Custom Fields. You need to be more specific.

**Comment by stefonarch** [comment]
Hm, I noticed this issue on my debian box. I rarely use qps, more ofter `top`.
I see now that on arch it _does_ save it.

Will edit it the report and try to find the diff.

**Comment by tsujan** [comment]
> I see now that on arch it does save it.

An old version in Debian?

**Comment by stefonarch** [comment]
Nope, bullseye unstable, buster has an too old qt version to compile.
Could be an issue in my home.
On arch I see 2 config files and it looks that both get updated on changing options...
```
stef@arch:~$ l .config/qps
totale 24K
drwxr-xr-x   2 stef stef  4,0K 16 dic 17.14 .
drwxr-xr-x 159 stef users  16K 16 dic 09.44 ..
-rw-r--r--   1 stef stef   382 16 dic 17.14 qps.conf
stef@arch:~$ l .config/qps/qps.conf 
-rw-r--r-- 1 stef stef 382 16 dic 17.14 .config/qps/qps.conf
```

**Comment by tsujan** [comment]
Two config files? The correct config file is `~/.config/qps/qps.conf`. `~/qps.conf` may be there for backward compatibility.

Apparently, I should take a look at Qps's messy code again. It couldn't be a pleasant experience and I'll definitely postpone it ;)

**Comment by stefonarch** [comment]
Switched to debian, and found ~/.qpsrc no idea when this was created, but it was updated too, besides ~/.config/qps/qps.conf.
Removed all and only the latter gopt recreated and issue is gone.

> It couldn't be a pleasant experience

It looks like hell, and I'm no coder. I tried to find out why "Thread" isn't translatable, found it at the end in misc.cpp but didn't manage to include it with lxqt-transupdate.

**Comment by tsujan** [comment]
> found ~/.qpsrc no idea when this was created, but it was updated too

It shouldn't. That's why I should check the code.

> It looks like hell

Oh, you have no idea ;) It won't be a surprise to me if translations have a problem..

We've made it work fine and removed lots of nonsense from the code but it's still messy. IMO, no feature should be added to Qps for now; only bug fixes and, especially, code cleanups.
