### ISSUE TITLE
There is no history info (on hard-coded tooltips)

### ISSUE THREAD

**Issue by tsujan** [lxqt/qps#321]
##### Expected Behavior

The user knows which hard-coded (translucent) tool-tip is shown when he/she moves the cursor over Qps' top bar.
##### Current Behavior

Some big tool-tips show up and disappear suddenly. It's hard to find them again.

##### Steps to Reproduce

If you move the mouse cursor on the top bar, you might see "flashes": a tool-tip might appear and disappear in a moment.

##### Context

When Qps was started (more that 20 years ago), Qt was poor compared to now. The original author had to invent various widgets and he did that quite skillfully. Now those widgets look alien and may not function as expected.

The top bar has a good design but its code may need lots of updates.
##### System Information

Latest git.

**Comment by stefonarch** [comment]
I see no issue with those, could depend on WM in use (openbox)?
![schermata-08-53-45](https://user-images.githubusercontent.com/10681413/127109485-11f1c79d-99f1-4b8b-8db8-6906cbe4179e.png)

**Comment by tsujan** [comment]
The tool-tip that's shown in your screenshot has no problem. There's a big tool-tip about "mini-history" that you'll see only if you're lucky ;)

**Comment by tsujan** [comment]
I found it:

![minihistory](https://user-images.githubusercontent.com/981076/127110423-69ec11c1-b45a-41b8-bc07-be264cb7e7d1.png)

**Comment by stefonarch** [comment]
Ok, this I've never seen indeed, I thought just "strange this minihistory tooltip", cannot make this visible in any way.

**Comment by tsujan** [comment]
I saw it only by chance: saw a flash and tried several times.

**Comment by tsujan** [comment]
OK, this is about deleting history items, which I did  along time ago to fix a memory leak. But it wasn't a leak.

However, if I restore it, the memory usage could easily reach > 100 MiB after a while. I think I should reduce the maximum number of history items for an acceptable memory usage. Trial and error will be needed.

**Comment by tsujan** [comment]
For now, I've run out of ideas. Suggestions are welcome. Let me explain the situation:

What I did 2 years ago (in https://github.com/lxqt/qps/commit/44619b53298733e23aad8791b6579051e62b21f6) was sacrificing "mini-history tooltips" for having a wide enough graph with a good memory usage.

We have 1200 history items. They can create a 1200-pixel wide graph, which is good. But to show mini-history tooltips when the cursor moves to the left, we need to remember *all processes for each of those items* (= moments = pixels). That could easily take more than 100 MiB of memory if enough time is passed. This amount of memory isn't so different from a memory leak, although, technically, it isn't a leak. It's simply ridiculous for a process monitor..

The memory usage would become acceptable if we had 120 history items but that would result in a 120-pixel wide graph, which is out of question.

Apps like KSysGuard don't show "mini-history"; their tooltips only show the current values.

**Comment by iamthesenate1** [comment]
Maybe writing the data to a temporary file (that would be deleted when qps closes) would be an option?

**Comment by tsujan** [comment]
> Maybe writing the data to a temporary file

Thanks! That hadn't occurred to me.

But the amount of the data is enormous. Writing them to a file and reading them from it would need considerable IO.

I think there's no way other than changing the purpose of the tooltip and only showing a static summary of the processes at the moment of its creation. However, if a working solution is found, having a mini-history on tooltips would be nice.

**Comment by iamthesenate1** [comment]
>But the amount of the data is enormous. Writing them to a file and reading them from it would need considerable IO.

I see what you mean... The purpose of displaying the resource usage accurately makes it (almost) impossible to implement such a function.

**Comment by tsujan** [comment]
> The purpose of displaying the resource usage accurately makes it (almost) impossible to implement such a feature.

Yes, unless we find a way of limiting its memory usage to ~10MiB or so.

**Comment by iamthesenate1** [comment]
I think the title should be edited to something more suggestive, like "reimplementation of the miniHistory tooltips" and adding the need help label. Also, if #327 is merged it should be referenced so as to anyone who can and wants to help, they could have all information in one pace and not have to look through a long thread of comments.

**Comment by tsujan** [comment]
Frankly, I don't think anyone will do anything about it. The code is like an old jungle that I and a few other devs got familiar with it after getting lost in it several times.

**Comment by shlyakpavel** [comment]
> Maybe writing the data to a temporary file (that would be deleted when qps closes) would be an option?

This will either consume RAM (in /tmp) or kill SSDs. I don't like the idea

**Comment by tsujan** [comment]
> This will either consume RAM (in /tmp)

True.

> ... or kill SSDs

I think it's good to minimize read/write everywhere but yes, it's especially good for SSD.

**Comment by tsujan** [comment]
In https://github.com/lxqt/qps/pull/406, I "solved" the problem by showing summaries, instead of "mini-histories". The summaries are gathered at the moment of cursor movement, and the horizontal position of the cursor isn't important.

I didn't remove the history code though, as it might be useful in future.
