### ISSUE TITLE
2 sorting indicators in header

### ISSUE THREAD

**Issue by tsujan** [lxqt/qps#324]
The following problem can be reproduced with all widget styles but it's more persistent with Fusion:

![two_sort_ind](https://user-images.githubusercontent.com/981076/128487858-5f2372a1-3948-4167-8ae0-82224233dd0a.png)

To create two sorting indicators (arrows), I click a header section adjacent to the sorted one and then *quickly* click the previous section. If I do it fast enough, two indicators will be seen.

With Kvantum and Breeze, the wrong indicator will disappear if the window is made inactive and active again.

I don't know if this is an old problem or a result of a Qt update. It doesn't affect functionality but can be confusing.

**Comment by shlyakpavel** [comment]
I can reproduce it :)
