### ISSUE TITLE
Strange magic. To be removed?

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qps#331]
https://github.com/lxqt/qps/blob/ffa327b28ff89bcfc641d2cc0fa8a27a8f7e2a98/src/misc.cpp#L675-L687
Any ideas what this 'm' magic may mean? I'd prefer to remove it

**Comment by tsujan** [comment]
Is it stranger than this?

https://github.com/lxqt/qps/blob/ffa327b28ff89bcfc641d2cc0fa8a27a8f7e2a98/src/misc.cpp#L912

IMO, the original developer was very skillful but had a terrible coding style and wrote everything that came to his mind. That's rare but possible.

Feel free to remove `MyThread` and `MyThread2` if you're sure they're redundant. And what's `flag_devel`?!
