### ISSUE TITLE
Complaint from rpmlint

### ISSUE THREAD

**Issue by luigino** [lxqt/qps#37]
```
qps.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/qps
The binary calls gethostbyname(). Please port the code to use getaddrinfo().
```

As in [src/lookup.cpp#L190](https://github.com/QtDesktop/qps/blob/master/src/lookup.cpp#L190).
See Ulrich Drepper's [explanation](http://udrepper.livejournal.com/16116.html).

**Comment by agaida** [comment]
erm - no - it will be more likely that we completely remove this stuff. Right now it has no infuence on any functionality.
