### ISSUE TITLE
Dark Mode Please!

### ISSUE THREAD

**Issue by Lonniebiz** [lxqt/qps#383]
I like the way this tool works, but desperately want it in a dark-mode theme. I'd love options to persist my desired background color and font-colors.

**Comment by tsujan** [comment]
Like any Qt apps, Qps follows the active Qt style.

**Comment by Lonniebiz** [comment]
Ok. I was using this package via [awesome](https://awesomewm.org/), so it wasn't clear to me how to change that. I'll figure it out.

**Comment by tsujan** [comment]
`qt5ct` should do it. It's the best choice for DEs without a Qt support.
