### ISSUE TITLE
Add .desktop strings to ts files

### ISSUE THREAD

**Issue by scootergrisen** [lxqt/qps#40]
I suggest adding the strings from the .desktop to be translated to the .ts files so translators can easily translate them.

**Comment by agaida** [comment]
if you know how to do this please go ahead

**Comment by scootergrisen** [comment]
I dont know how its done.
Some .desktop files seem to have "_" in front like on https://github.com/geany/geany/blob/master/geany.desktop.in and i think when they have that it means that the string is translated elsewhere.
Like in https://github.com/geany/geany/blob/master/po/da.po#L19-L33
Maybe its [gettext](https://www.gnu.org/software/gettext/manual/) but i dont know much about it. Just the translator parts.

**Comment by agaida** [comment]
And thats exactly the problem i have - i only know the hosting and technical part of webate (partly).
And a very wild guess is that i will leave out anything that add another bunch of problems (right now) - still struggeling with the basics - ok, weblate is up and running and looks like it was the right decision.

But it still need some fine tuning - settings, machine translation, checks etc. i guess that will be my pet project beside the other things for the next few weeks.

**Comment by tsujan** [comment]
As far as I can tell, ts files are created for what's in the code, not for what may be installed in addition to it. So, I don't think desktop files could be unified with ts files.

**Comment by tsujan** [comment]
In other words, ts files are created by Qt; desktop files aren't.

**Comment by scootergrisen** [comment]
You can write a comment for translations so they know the .desktop file can be translated also.
It seems many project dont have instructions that the .desktop file should be translated so it seems many translator dont translate it and i think its because they dont know about it.

So i think the best solution is to add the strings to where the other strings are so its in the same place.
If not then add a instructions some where.

**Comment by agaida** [comment]
To be honest - my suggestion would be: Ask some people who know about translations and pitfalls - we use weblate, so my guess is that it would be the right way to talk with the guys about problems and about any other questions.

**Comment by agaida** [comment]
btw - there is this existing bug #15 - the real problem with qps is that the very most strings are not translatable. And that is a real problem imho. If we have only the desktop snippets not included in the weblate thing - i can live with for a while. But a application with lots of strings, only 30 to translate and (wild guess) only two or three of them are really used - thats what i would call a problem.

**Comment by agaida** [comment]
brand new code from the last century? Need to be rewritten after 20 year? Oh no!! ;)

**Comment by tsujan** [comment]
OK, I'd forgotten you knew it.
