### ISSUE TITLE
Different RAM usage show by qps and other programs

### ISSUE THREAD

**Issue by Bluey26** [lxqt/qps#472]
##### Expected Behavior

The same way to measure ram usage by different programs.

##### Current Behavior

`free -m` shows a different value for 'used' ram than `qps`

Cached/Buffer by `free -m` command is almost the same as Cached+Buffer values present in qps.

In the other hand, Conky panel also monitors ram usage(RSS ram?)

`$mem` is the variable used by Conky, which does not match `free -m` value, but its really closer, much more than the one shown by qps.

##### Steps to Reproduce (for bugs)

1. Opening qps, checking the ram usage in the MEM bar in the UI
2.Running `free -m` or using conky panel to see the ram usage
##### Context

This seems to happen also in X11, not related to labwc or wayland (i think).
I do not recall this before 2.0 but its probable that the differences still are present in the previous version, and i just did not noticed it.

~~Maybe it is just that qps uses MEM(RSS-SHARE) to measure the RAM usage and the other programs are using RSS(bigger number)~~ --> I summed all the RSS-SHARE values and they were inferior to the one shown as 'Used'.

In the other hand, i also summed the RSS(Resident Set Size) values shown by qps in the UI and the number was closer to the ones shown by `free -m` and `conky`

##### System Information

* Distribution & Version: Archlinux
* Kernel: 6.8.9-arch1-1
* Qt Version: 6.7
* lxqt-build-tools Version: 2.0.0-1
* Package version:  2.9.0-1

I attach some pictures with the numbers.

Qps:
![screen-qps](https://github.com/lxqt/qps/assets/143142826/c0d1c586-3418-4c5f-bb5e-3c5d8d802d1b)

Summed RSS values:
![screen-summed-RSS](https://github.com/lxqt/qps/assets/143142826/81ca3c24-0369-44b4-ba0c-fd86e8b2d3d2)

`free -m` output
![screen-free](https://github.com/lxqt/qps/assets/143142826/65b78194-45dd-4694-8e4a-46934f38a31e)

Conky shown value
![screen-conky](https://github.com/lxqt/qps/assets/143142826/6ae2a38c-2921-45d7-af81-6eb74bdcba03)

**Comment by tsujan** [comment]
As far as I've seen, this isn't specific to Qps. Different apps may show different RAM usages, perhaps, based on different interpretations of "usage". So, I don't think it's a bug.

Leaving it open until I find time again and check Qps's code -- not soon.

**Comment by Bluey26** [comment]
Hello.

I tested the commit, using:

```
source=("git+https://github.com/lxqt/qps#commit=13aa952")
sha256sums=('SKIP')
```

in my `PKGBUILD,` obtained from the `qps` AUR official repository.

Upon measuring the values, i can confirm that the approach makes the `Used MEM` field to be almost as exactly in the 3 programs i have used (`free -h` and the `conky` panel,which used to match between those two before).

I could say that in my opinion the method is fine, and i also have seen that if the user has not the corresponding package(present since kernel 3.1.4), the program will use the current method which is a good way to do it.

The only thing that still does not match is the summed RSS (Resident Set Size) or the MEM fields, i would expect that one of those 2 fields would match the Used or the used+Cached memory, but this does not. This is a small detail which i want to make you notice, i summed the values and they did not match. (maybe could be changed in the future).

I like this commit so i would merge it into the main code :D (and would close this issue).

Thanks @SnAgCu and @tsujan for the work!

**Comment by tsujan** [comment]
Thanks for testing! It's merged now.

**Comment by SnAgCu** [comment]
@Bluey26, to clarify:

> Qps 'Used' field: 2493Mb (2493*0,95367431640625 ) = 2377,51007080078125 Mib ~ 2,37GiB which is aceptable IMO.
> free -h 'used' field: 2.4Gi
> Conky RAM usage: 2,45Gib

qps actually displays the value in mebibytes (MiB), there is an open issue (#215) about it.
So 2493MiB = 2.43Gib.
All three apps are doing MemTotal - MemAvailable, which are just lines in the /proc/meminfo file, it changes constantly so different apps will show different values depending on what exact moment they read it:

![screenshot-d78c9f1e](https://github.com/lxqt/qps/assets/125407598/d090f7c0-fae0-486e-8d12-e983cb8e47c1)

> The only thing that still does not match is the summed RSS (Resident Set Size) or the MEM fields, i would expect that one of those 2 fields would match the Used or the used+Cached memory, but this does not.

That is expected, as MemAvailable looks at other places (read the commit message at http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0a).

**Comment by Bluey26** [comment]
Thanks for the explanation @SnAgCu 

Yes, i was opening/minimizing the apps during the measurement so they should be the same value, as you show in the pictures.

> as MemAvailable looks at other places...

I see, i was wondering what was the correlation between the used ram and the other value, which didnt match because of what you said, i expected it to be the sum, but there's something different going on.

**Comment by tsujan** [comment]
> qps actually displays the value in mebibytes (MiB), there is an open issue (https://github.com/lxqt/qps/issues/215) about it.

@SnAgCu, would you please fix that too?
