### ISSUE TITLE
Pressing Ctrl+A in the search bar does nothing

### ISSUE THREAD

**Issue by jroovy** [lxqt/qps#473]
##### Expected Behavior

Pressing Ctrl+A selects all text typed in the search bar

##### Current Behavior

Ctrl+A does nothing in the search bar

##### Steps to Reproduce (for bugs)

1. Type in search bar
2. Press Ctrl+A to select all text
3. 
4. 

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 6.8.9
* Qt Version: 6.7.0
* lxqt-build-tools Version: 
* Package version: 2.9.0

**Comment by tsujan** [comment]
`Ctrl+A` is for selecting all filtered rows.
