### ISSUE TITLE
Preference 'Remember position' not obeyed after system restart

### ISSUE THREAD

**Issue by seniordevel** [lxqt/qps#484]
I set the preference 'Remember position'.
As it works fine in a session, the preference is forgotten after system restart.
I launch QPS with the autostart feature, with parameter 'mini'.

##### Expected Behavior
After system restart, QPS should remember window size and and position

##### Current Behavior
After system restart window size and position is different compared to last session

##### Possible Solution
Once it is set, save position and size to a file, read the data on next launch

##### Steps to Reproduce (for bugs)
1. Set remember Position in preferences
2. Resize window, change position
3. restart system
4. autostart QPS with parameter mini

##### System Information
I am on Linux 6.10.13-3-MANJARO (x86_64), 
KDE on x11
QPS 2.9.0

**Comment by tsujan** [comment]
> the preference is forgotten after system restart.

That means the DE doesn't terminate Qps's process "gracefully" and just kills it.

> KDE on x11

KDE should do it correctly, unless qps is excluded in a setting or there's a general problem in the KDE session. Please check the parent process of qps with `pstree` (in a terminal). Do you have a problem with another app that's running on ending the KDE session and doesn't save its configuration?

**Comment by seniordevel** [comment]
Thank you, solved

**Comment by seniordevel** [comment]
> How was it solved?

As you guessed correctly, I had problems with proper shutdown/restart after applying a system update.
After fixing my shutdown issue, the QPS issue #484 was gone too. Thanks again.

[ off-topic, but to answer your question thoroughly: Here I found instructions to solve my shutdown issue:
[https://bbs.archlinux.org/viewtopic.php?id=297684&p=2](url) , 29 ]

**Comment by tsujan** [comment]
Thanks for the explanation. It might be helpful to others too.
