### ISSUE TITLE
Crash with 'Select custom fields'

### ISSUE THREAD

**Issue by seniordevel** [lxqt/qps#487]
Selecting any custom field item always results in a crash.

Note:  
Just opening 'Select custom fields...' 2 times successively (without doing any selection) also triggers crashes reliable. 
menu-bar > Fields > Select custom fields... => crash

In contrast 'Add field' from column bar by right click always works fine.

##### Steps to Reproduce (for bugs)
1. Click menu-bar > Fields > Select custom fields...
2. Click any item checkbox in the 'Select custom fields window'
3. QPS crashes

--- OR ---
1. Click menu-bar > Fields > Select custom fields...
2. Click close button (at bottom or at top right)
3. Click menu-bar > Fields > Select custom fields...
4. QPS crashes

                                --->

##### System Information
Operating System: Manjaro Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.8.0
Qt Version: 6.7.2
Kernel Version: 6.10.13-3-MANJARO (64-bit)
Graphics Platform: X11
Graphics Processor: KAVERI

QPS 2.9.0

**Comment by tsujan** [comment]
Not reproducible in either case.

Please add the backtrace(s) of the crash(s) you encounter. The issue will be reopened if something suspicious about Qps exists in it/them.

**Comment by seniordevel** [comment]
This is always reproducible on my system


> add the backtrace(s) of the crash(es) 
How to do so ?

**Comment by tsujan** [comment]
> How to do so ?

See if any qps coredump, that's related to those crashes, exists in `/var/lib/systemd/coredump` (if not, make it crash and check again). If there is one, do this in a terminal:

```
coredumpctl gdb qps
<answer no to the prompt, if any>
where
```
and *attach what comes after `where`*. Then you could press `q` to exit.

**Comment by shlyakpavel** [comment]
Also, you can try connecting with gdb to the process before the crash and checking bt right after

**Comment by tsujan** [comment]
> Also, you can try connecting with gdb to the process before the crash and checking bt right after

That's a little less easy, when an Arch-based system provides coredumps ;)

**Comment by seniordevel** [comment]
I created a fresh dump just now:

`coredumpctl gdb qps
           PID: 38472 (qps)
           UID: 1000 (ingo)
           GID: 1001 (ingo)
        Signal: 11 (SEGV)
     Timestamp: Wed 2024-10-30 20:58:26 CET (56s ago)
  Command Line: /usr/bin/qps
    Executable: /usr/bin/qps
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-qps@bfba2a7370424194bdbc3468691d8642.service
          Unit: user@1000.service
     User Unit: app-qps@bfba2a7370424194bdbc3468691d8642.service
         Slice: user-1000.slice
     Owner UID: 1000 (ingo)
       Boot ID: 9975fd893e054760aa35ea4d77f8ecb4
    Machine ID: b5bca586a4334c5688f158f69e53176c
      Hostname: ingo-tobefilledbyoem
       Storage: /var/lib/systemd/coredump/core.qps.1000.9975fd893e054760aa35ea4d77f8ecb4.38472.1730318306000000.zst (present)
  Size on Disk: 3.6M
       Message: Process 38472 (qps) of user 1000 dumped core.
                
                Stack trace of thread 38472:
                #0  0x00005d887cc0f724 n/a (qps + 0x46724)
                #1  0x00007c74fa34cedd _ZN7QWidget5eventEP6QEvent (libQt6Widgets.so.6 + 0x14cedd)
                #2  0x00007c74fa2fc8cc _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt6Widgets.so.6 + 0xfc8cc)
                #3  0x00007c74f9145aa8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt6Core.so.6 + 0x145aa8)
                #4  0x00007c74fa34a6c9 _ZN14QWidgetPrivate11show_helperEv (libQt6Widgets.so.6 + 0x14a6c9)
                #5  0x00007c74fa34aa53 _ZN14QWidgetPrivate10setVisibleEb (libQt6Widgets.so.6 + 0x14aa53)
                #6  0x00007c74fa56bf6f _ZN14QDialogPrivate10setVisibleEb (libQt6Widgets.so.6 + 0x36bf6f)
                #7  0x00005d887cbfd8bd n/a (qps + 0x348bd)
                #8  0x00007c74f91a3397 n/a (libQt6Core.so.6 + 0x1a3397)
                #9  0x00007c74f9d243c4 _ZN7QAction8activateENS_11ActionEventE (libQt6Gui.so.6 + 0x5243c4)
                #10 0x00007c74fa4d1779 n/a (libQt6Widgets.so.6 + 0x2d1779)
                #11 0x00007c74fa4d3673 n/a (libQt6Widgets.so.6 + 0x2d3673)
                #12 0x00007c74fa34d376 _ZN7QWidget5eventEP6QEvent (libQt6Widgets.so.6 + 0x14d376)
                #13 0x00007c74fa2fc8cc _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt6Widgets.so.6 + 0xfc8cc)
                #14 0x00007c74fa301e59 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt6Widgets.so.6 + 0x101e59)
                #15 0x00007c74f9145aa8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt6Core.so.6 + 0x145aa8)
                #16 0x00007c74fa2f3f9d _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb (libQt6Widgets.so.6 + 0xf3f9d)
                #17 0x00007c74fa363b40 n/a (libQt6Widgets.so.6 + 0x163b40)
                #18 0x00007c74fa364c20 n/a (libQt6Widgets.so.6 + 0x164c20)
                #19 0x00007c74fa2fc8cc _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt6Widgets.so.6 + 0xfc8cc)
                #20 0x00007c74f9145aa8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt6Core.so.6 + 0x145aa8)
                #21 0x00007c74f9978140 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt6Gui.so.6 + 0x178140)
                #22 0x00007c74f99e7724 _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Gui.so.6 + 0x1e7724)
                #23 0x00007c74f57acb87 n/a (libQt6XcbQpa.so.6 + 0x51b87)
                #24 0x00007c74f8b08299 n/a (libglib-2.0.so.0 + 0x5d299)
                #25 0x00007c74f8b6aec7 n/a (libglib-2.0.so.0 + 0xbfec7)
                #26 0x00007c74f8b07795 g_main_context_iteration (libglib-2.0.so.0 + 0x5c795)
                #27 0x00007c74f93a82bd _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x3a82bd)
                #28 0x00007c74f914ff66 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x14ff66)
                #29 0x00007c74f914a11d _ZN16QCoreApplication4execEv (libQt6Core.so.6 + 0x14a11d)
                #30 0x00005d887cbe0eac n/a (qps + 0x17eac)
                #31 0x00007c74f9630e08 n/a (libc.so.6 + 0x25e08)
                #32 0x00007c74f9630ecc __libc_start_main (libc.so.6 + 0x25ecc)
                #33 0x00005d887cbe1145 n/a (qps + 0x18145)
                
                Stack trace of thread 38475:
                #0  0x00007c74f971663d __poll (libc.so.6 + 0x10b63d)
                #1  0x00007c74f8b6ae0d n/a (libglib-2.0.so.0 + 0xbfe0d)
                #2  0x00007c74f8b07795 g_main_context_iteration (libglib-2.0.so.0 + 0x5c795)
                #3  0x00007c74f93a82bd _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x3a82bd)
                #4  0x00007c74f914ff66 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x14ff66)
                #5  0x00007c74f923d650 _ZN7QThread4execEv (libQt6Core.so.6 + 0x23d650)
                #6  0x00007c74f8f70f0e n/a (libQt6DBus.so.6 + 0x2df0e)
                #7  0x00007c74f92cd237 n/a (libQt6Core.so.6 + 0x2cd237)
                #8  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #9  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 38476:
                #0  0x00007c74f971663d __poll (libc.so.6 + 0x10b63d)
                #1  0x00007c74f87a020b n/a (libxcb.so.1 + 0xd20b)
                #2  0x00007c74f87a1f3d xcb_wait_for_event (libxcb.so.1 + 0xef3d)
                #3  0x00007c74f57a9c99 n/a (libQt6XcbQpa.so.6 + 0x4ec99)
                #4  0x00007c74f92cd237 n/a (libQt6Core.so.6 + 0x2cd237)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 38479:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00007c74e58cecae n/a (libgallium-24.2.4-arch1.0.1.so + 0xcecae)
                #3  0x00007c74e58ab6bc n/a (libgallium-24.2.4-arch1.0.1.so + 0xab6bc)
                #4  0x00007c74e58cebdd n/a (libgallium-24.2.4-arch1.0.1.so + 0xcebdd)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 39971:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e7e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                #2  0x00007c74f92d1bf8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x2d1bf8)
                #3  0x00007c74f92cb852 n/a (libQt6Core.so.6 + 0x2cb852)
                #4  0x00007c74f92cd237 n/a (libQt6Core.so.6 + 0x2cd237)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 38481:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00007c74e58cecae n/a (libgallium-24.2.4-arch1.0.1.so + 0xcecae)
                #3  0x00007c74e58ab6bc n/a (libgallium-24.2.4-arch1.0.1.so + 0xab6bc)
                #4  0x00007c74e58cebdd n/a (libgallium-24.2.4-arch1.0.1.so + 0xcebdd)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 39973:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e7e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                #2  0x00007c74f92d1bf8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x2d1bf8)
                #3  0x00007c74f92cb852 n/a (libQt6Core.so.6 + 0x2cb852)
                #4  0x00007c74f92cd237 n/a (libQt6Core.so.6 + 0x2cd237)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 38482:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00007c74e58cecae n/a (libgallium-24.2.4-arch1.0.1.so + 0xcecae)
                #3  0x00007c74e58ab6bc n/a (libgallium-24.2.4-arch1.0.1.so + 0xab6bc)
                #4  0x00007c74e58cebdd n/a (libgallium-24.2.4-arch1.0.1.so + 0xcebdd)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 38480:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00007c74e58cecae n/a (libgallium-24.2.4-arch1.0.1.so + 0xcecae)
                #3  0x00007c74e58ab6bc n/a (libgallium-24.2.4-arch1.0.1.so + 0xab6bc)
                #4  0x00007c74e58cebdd n/a (libgallium-24.2.4-arch1.0.1.so + 0xcebdd)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 39970:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e7e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                #2  0x00007c74f92d1bf8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x2d1bf8)
                #3  0x00007c74f92cb852 n/a (libQt6Core.so.6 + 0x2cb852)
                #4  0x00007c74f92cd237 n/a (libQt6Core.so.6 + 0x2cd237)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 38477:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00007c74e58cecae n/a (libgallium-24.2.4-arch1.0.1.so + 0xcecae)
                #3  0x00007c74e58ab6bc n/a (libgallium-24.2.4-arch1.0.1.so + 0xab6bc)
                #4  0x00007c74e58cebdd n/a (libgallium-24.2.4-arch1.0.1.so + 0xcebdd)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 38478:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00007c74e58cecae n/a (libgallium-24.2.4-arch1.0.1.so + 0xcecae)
                #3  0x00007c74e58ab6bc n/a (libgallium-24.2.4-arch1.0.1.so + 0xab6bc)
                #4  0x00007c74e58cebdd n/a (libgallium-24.2.4-arch1.0.1.so + 0xcebdd)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 39972:
                #0  0x00007c74f969ba19 n/a (libc.so.6 + 0x90a19)
                #1  0x00007c74f969e7e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                #2  0x00007c74f92d1bf8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x2d1bf8)
                #3  0x00007c74f92cb852 n/a (libQt6Core.so.6 + 0x2cb852)
                #4  0x00007c74f92cd237 n/a (libQt6Core.so.6 + 0x2cd237)
                #5  0x00007c74f969f39d n/a (libc.so.6 + 0x9439d)
                #6  0x00007c74f972449c n/a (libc.so.6 + 0x11949c)
                ELF object binary architecture: AMD x86-64
`

**Comment by tsujan** [comment]
You didn't do it as I suggested ;) What comes after `where` is *human-redable*, while a human being like me can read your attached trace with difficulty.

Anyway, the trace doesn't show that the crash is caused by qps — as I suspected. Something else may be wrong.

**Comment by seniordevel** [comment]
(gdb) attach 41715
Attaching to process 41715
ptrace: Operation not permitted.
(gdb) 

Process PID is correct.

**Comment by seniordevel** [comment]
> You didn't do it as I suggested ;) What comes after `where` is _human-redable_, while a human being like me can read your attached trace with difficulty.
> 
> Anyway, the trace doesn't show that the crash is caused by qps — as I suspected. Something else may be wrong.

I tried my best to do as you suggested.
Not sure what is wrong.

So, what to do next?

**Comment by tsujan** [comment]
> I think debug info is required for human readable output.

I [told](https://github.com/lxqt/qps/issues/487#issuecomment-2448241254) that you could say "no". But it isn't important now.

> So, what to do next?

Nothing. The trace doesn't show a problem in qps itself. The crash may happen for various reasons and might be fixed after an upgrade.

**Comment by seniordevel** [comment]
Your decision:
We can stop here, as I am fine with the software as it is.
I still can use the context menu to add fields without crashes.
Thus my interest to fix this bug is very limited.

**Comment by seniordevel** [comment]
> I [told] that you could say "no". But it isn't important now.

Yes, I followed your instruction, ans in fact I replied with NO on my first try !!!
I sent the output and you said 'not human readable'.

Then I tried a second time and answered YES.  But this was my own SECOND try.

**Comment by tsujan** [comment]
> Thus my interest to fix this bug is very limited.

Those who know me also know that I wouldn't let it go if I was sure that it was a bug in Qps.

The latest stable Qt is 6.8.0 and the latest stable Plasma is 6.2.2. (The latest version of qps will become 2.10.0 soon.)
