### ISSUE TITLE
Language value changed from "da" to "da_DK"

### ISSUE THREAD

**Issue by scootergrisen** [lxqt/qps#82]
Why was "da" changed to "da_DK" in https://github.com/lxqt/qps/commit/fe1f8470bb2322a59a7b503294570cb5e374b3dc#diff-ccd42e734cc98b6cd957b075d3448605 ?

I would like this not to happen in the future.

Can i change it on Weblate?

**Comment by agaida** [comment]
just change it back per PR - sorry such things happend from time to time.

**Comment by scootergrisen** [comment]
How does that change it on Weblate?
It would not be smart to make a pull request and then wait and perhaps changes have been made and then its overwritten on Weblate.

**Comment by scootergrisen** [comment]
German and polish might have the same problem in case anyone wants to correct them to.
```

qps_de.ts:

<TS version="2.1" language="de_DE">

qps_pl.ts:

<TS version="2.1" language="pl_PL">

```

**Comment by tsujan** [comment]
Strange! It may not be caused by weblate because none of these happened for FeatherPad, which uses weblate too.

**Comment by agaida** [comment]
It was introduced by a massive patch in June - and has more or less no effect. So - we should change it, but: weblate ignore it, the translations work - all things fine, will change it later.

**Comment by scootergrisen** [comment]
Are there any smart way to download all LXQt translations?

**Comment by agaida** [comment]
could think of some rsync or wget magic - but - out of the box - no, i'm afraid.

**Comment by agaida** [comment]
long done
